MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/FAIR/20171220/X-101-32x8d"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
    OUT_CHANNELS: 256
  CLASSIFIER_CLS:
    NUM_CLASSES: 10 
  CLASSIFIER_ORIENT:
    NUM_CLASSES: 3
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 8
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    EXCLUDE_LABELS: (0, 3)
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  RESNETS:
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
  MASK_ON: True
  CLASSIFIER_CLS_ON: True 
  CLASSIFIER_ORIENT_ON: True 
DATASETS:
  TRAIN: ("coco_timeline_train",)
  TEST: ("coco_timeline_val",)
INPUT:
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 833
  MAX_SIZE_TEST: 1024
DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (18000, 24000)
  # Epoch = (MAX_ITER * IMS_PER_BATCH) / #dataset
  MAX_ITER: 26000
  IMS_PER_BATCH: 2 
  CHECKPOINT_PERIOD: 1000 
OUTPUT_DIR: "models/e2e_mask_rcnn_X_101_32x8d_FPN_save"
